# Generated by Django 2.1.5 on 2019-02-11 18:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[1-9]\\d{9}$|^[1-9]\\d{12}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('suspendido', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitetest.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('suspendido', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitetest.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField(max_length=150)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitetest.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=3, default=0.12, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('ruc', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[1-9]\\d{9}$|^[1-9]\\d{12}$')])),
                ('direccion', models.CharField(blank=True, max_length=265)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('cuenta_ahorros', 'Cuenta Ahorros'), ('cuenta_corriente', 'Cuenta Corriente')], max_length=25, null=True)),
                ('numero_cuenta', models.BigIntegerField(blank=True, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=150, null=True)),
                ('vendedor_telefono', models.BigIntegerField(blank=True, null=True)),
                ('vendedor_correo', models.EmailField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitetest.Proveedor'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitetest.Factura'),
        ),
    ]
