# Generated by Django 2.1.5 on 2019-04-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comprobantes',
            new_name='Comprobante',
        ),
    ]
