# Generated by Django 2.1.5 on 2019-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0002_auto_20190410_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
