# Generated by Django 2.1.5 on 2019-06-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0004_auto_20190606_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='conteo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cargar.ConteoComprobante'),
            preserve_default=False,
        ),
    ]
