# Generated by Django 2.1.5 on 2019-06-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0006_comprobante_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='conteo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargar.ConteoComprobante'),
        ),
    ]
