# Generated by Django 2.1.5 on 2019-06-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0009_auto_20190611_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcarga',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
