# Generated by Django 2.1.5 on 2019-06-12 21:38

import cargar.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargar', '0010_errorcarga_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('oficio', models.FileField(upload_to=cargar.models.user_directory_path)),
                ('tipo', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('institucion', models.CharField(max_length=255)),
                ('conteo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cargar.ConteoComprobante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
