# Generated by Django 2.1.5 on 2019-06-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0012_auto_20190612_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oficio',
            old_name='entrantes',
            new_name='entrante',
        ),
    ]
