# Generated by Django 2.1.5 on 2019-06-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0013_auto_20190612_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteocomprobante',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
