# Generated by Django 2.1.5 on 2019-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0014_conteocomprobante_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='errorcarga',
            name='archivo',
            field=models.CharField(blank=True, default='Sin error', max_length=255, null=True),
        ),
    ]
